name: Process Videos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process-videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14'

    - name: Setup yt-dlp
      uses: AnimMouse/setup-yt-dlp@v1

    - name: Install dependencies
      run: |
        npm install

    - name: Run script
      run: |

        # video data
        videodata="./data/videos"

        # playlist URLS
        declare -A playlists=(
            ["2023"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIZ6OtS-D6PUpn4TflgVqi7R"
            ["2022"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIYq6FBpOBHfHchjI0zTYINO"
            ["2021"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIbQgPDRsUHiawVtahvShN8X"
            ["2020"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIaarwTpOzGg4DXXVLWy2GVU"
            ["2019"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIZXGbpAdjpIP9cuuJYfOW-F"
            ["2018"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIaNfzV_-f0aYvrpAZAzjhIl"
            ["2017"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIYAk9rAz1CQmE9Pzn8G_hrq"
            ["2016"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIZtQ0PqjW341QIWrqPPkQXi"
            ["2015"]="https://www.youtube.com/playlist?list=PLm8zJ0HKEJIZz_vKS1amJguyAEIiTtxjw"
        )
        
        echo "Get Youtube Metadata for all Playlists"
        for year in "${!urls[@]}"; do
          yt-dlp --ignore-errors --write-info-json --skip-download -o "$videodata/$year/%(title)s [%(id)s].%(ext)s" ${urls[$year]}
        done

        find . -type f -name "*\[PL*\]*"  -exec rm {} \;

        # echo "Get VTT's for all videos"
        # ./bin/get-all-subs.sh ./data/videos

        # echo "Generate word counts from VTT's"
        # node ./bin/wordcount.js ./data/videos ./data/wordcount.txt
        # node ./bin/wordcount.js ./data/videos ./data/wordcount_video_stats.txt --include-video-stats

        # echo "Generate all Topics from VTT's"
        # ./bin/gen-all-topics.sh

        # echo "Compile DB's"
        # node ./bin/compile-db.js ./data/videos ./data/db.json

    # - name: Commit and push changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git checkout -b build
    #     git add ./data
    #     git commit -m "Update data files"
    #     git push -f origin build
